name: AntiBuild
version: '${version}'
main: dev.nikipro50.antibuild.AntiBuild
api-version: '1.13'
load: STARTUP
authors: [nikipro50]
description: Use a command for break and build in your server!
commands:
  build:
    permission: build.use
    description: Toggle build mode
permissions:
  build.*:
    children:
      - build.use
    default: op
    description: Use all functions of plugin!
  build.use:
    default: op
    description: Use /build command
